### ISSUE TITLE
Bug - new game is not saved if nothing was done

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#106]
**Describe the bug**
When starting a new adventure and immediately saving, the game keeps the map seed but does not retain the difficulty.

**To Reproduce**
1. Start a new adventure.
2. Save immediately.
3. Reopen the game.

**Expected behavior**
The game should boot straight into the map, skipping the difficulty selection screen without resetting the map seed.

**Comment by evanbowman** [comment]
It seems that the game is saved, but the setting screen reappears, as well as the zone introduction screen.

This fix (e9dfb6437a35edfe802673a3b2b8db2e98091a58) for re-ordering the zone image screen and the settings screen fixed part of the problem: the game no longer displays the settings screen when saving immediately and reloading a game.

But the zone intro image is still displayed, because it displays depending on the player's current map location, which, if you save immediately, is unchanged. Displaying the zone intro is somewhat of a minor issue, and perhaps not worth fixing.
