### ISSUE TITLE
Stuck on an event? Neutral 2.2 and Neutral 2.3

### ISSUE THREAD

**Issue by tolik518** [evanbowman/skyland-beta#21]
Entering the [neutral 2.2](https://github.com/evanbowman/skyland-beta/blob/3bcc641ea82f05860cc005a16349ca4a1d8541de/scripts/event/neutral/2/2.lisp) and [neutral 2.3](https://github.com/evanbowman/skyland-beta/blob/aec9b02b3bdf3ede090587bb77e8a458b90c88c8/scripts/event/neutral/2/3.lisp)  no dialog starts their ship is just floating and I can't attack them as it says `castle may be friendly`. The problem is most probably not exclusive for these two events. 

Could it be because I have some cloak blocks or because my isle is max size?
I haven't looked to much into it since I really wanted to continue the rounds - so my workaround 
was to build a drone bay and attack it with a drone (#19).

**Comment by evanbowman** [comment]
I think it may happen when an island reaches the max size, I'll have to look into it!
I previously tried to fix this with a patch in this file https://github.com/evanbowman/skyland-beta/blob/fa4af116606e91462514d9dc7537ef6bfe5d60e6/source/skyland/scene/fadeInScene.cpp#L112

The game invokes a script callback function called on-converge when the opponent's island stops moving towards the player, I think the callback must not have happened. Shouldn't be too hard to fix

**Comment by evanbowman** [comment]
Fixed in a new release. The issue involved a scene transition bug. The screen fades are handled by a class called FadeInScene, which derives from a WorldScene class. Scenes in the codebase implement state changes by allocating and returning a new scene in their update() function. WorldScene allocates a dialog scene, and then FadeInScene throws it out here: https://github.com/evanbowman/skyland-beta/blob/2793f97d1c600ba63052aa5b3b636494c7e058b0/source/skyland/scene/fadeInScene.cpp#L52
So the dialog never runs. Fixed by telling the WorldScene implementation not to process events and allocate new scenes: 
https://github.com/evanbowman/skyland-beta/blob/2793f97d1c600ba63052aa5b3b636494c7e058b0/source/skyland/scene/fadeInScene.cpp#L42
