### ISSUE TITLE
Highscore: Show difficulty settings / Gold / Ship / Flag

### ISSUE THREAD

**Issue by tolik518** [evanbowman/skyland-beta#24]
As for now only the highscore and the time is getting sent with the QR code.
I think it would be interesting to see at least the difficulty setting, gold and the total value of the ship (which is also calculated into the score I guess?). 

Since syncing macrocosm via the QR code is possible I thought it would be also a cool idea if you could sync the ship before the last fight and after the last fight (since rewind is implemented I figured it wouldn't be that hard to access the before ship).

It would be also a nice enhancement if the flag of the player is also gets sent and shown next to the name. I guess abuse would be possible with that, but as for right now, same goes for name and country I guess.

Aside from these being interesting addition they could expose potential cheaters (at least someone cheating himself a shitload of gold or invincibility)

**Comment by evanbowman** [comment]
Good idea!
Difficulty settings actually are sent (sort of), just not displayed on the website, I can display them. Sending ships would be possible, displaying images of them on the highscore website will take some additional work, because I'd have to write some code to render images of player's island on the webserver. Sending the player's flag and displaying it would be easy, as I can just encode the flag image directly into the qrcode.

In order of least to most difficult:
1) displaying the difficulty setting (already encoded in qrcode)
2) displaying gold and ship value
3) displaying the player's flag
4) displaying the player's island

I'll work on adding these things starting with the easiest ones

**Comment by evanbowman** [comment]
I might start by encoding flags and displaying them on the website, because it's easy enough to do, and I think it's a cool idea.

**Comment by evanbowman** [comment]
Ok, difficulty now displays on the website! That only took about five minutes :)

Next, I'll work on displaying the player's flag.

**Comment by tolik518** [comment]
> Good idea!
> Difficulty settings actually are sent (sort of), just not displayed on the website, I can display them. Sending ships would be possible, displaying images of them on the highscore website will take some additional work, because I'd have to write some code to render images of player's island on the webserver. Sending the player's flag and displaying it would be easy, as I can just encode the flag image directly into the qrcode.
> 
> In order of least to most difficult:
> 1) displaying the difficulty setting (already encoded in qrcode)
> 2) displaying gold and ship value
> 3) displaying the player's flag
> 4) displaying the player's island
> 
> I'll work on adding these things starting with the easiest ones

I'm glad you liked the idea :)

**Comment by evanbowman** [comment]
Flags will now display on the highscore site with future uploads. I assigned the default flag to all pre-existing uploads.
