### ISSUE TITLE
ENHANCEMENT - minimap

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#37]
Sometimes in lategame it can be very hard to try and keep track of your/enemy castle since its too big to fit on screen, which leads to pausing the game trying to find places to repair, a minimap similar to the one showing weapon trajectory showing the damaged places would make the lategame a lot more fluid.

**Comment by evanbowman** [comment]
Yeah, late game can get pretty chaotic, personally sometimes I place a targeting-computer depending on what strategy I'm playing with, so I can focus on repairs and other stuff. In early versions of the game, you had to manually position your crew, but I ended up automating that part, because with a lot of crew members it became impossible to manage with all the other stuff going on in a level.

Sometimes I've thought about ways to help players automate repairs, but I haven't decided on anything specific. e.g. some sort of automation block that automates rebuilding destroyed hull (but maybe people would unexpectedly run out of resources if construction was automated, I'm not sure). The minimap could be helpful, that's an idea I haven't thought of! I'll play around with that concept a bit.

At one point I had a shortcut in the game where, when viewing the enemy castle, you could tap the R button to jump to the most recently destroyed block on your own island, but it only worked for one coordinate and wasn't enough to be helpful.

**Comment by evanbowman** [comment]
I added a minimap option to the SELECT menu in this release: https://github.com/evanbowman/skyland-beta/releases/tag/2024.10.30.0

The minimap currently only appears at certain times due to video memory limitations on the gameboy and due to how the minimap overlaps with certain menus. I'll work on making it show up in more places.

**Comment by evanbowman** [comment]
I'll try to continue displaying the minimap in more parts of the game. I tried displaying it with the construction menu open, but the minimap intersects with the block picking selector. So I tried to bump the minimap up to the top right corner when opening the construction menu, but then on large levels the minimap sometimes covers up the cursor. Screen space is kind of limited :)

**Comment by Doronimmo** [comment]
> I'll try to continue displaying the minimap in more parts of the game. I tried displaying it with the construction menu open, but the minimap intersects with the block picking selector. So I tried to bump the minimap up to the top right corner when opening the construction menu, but then on large levels the minimap sometimes covers up the cursor. Screen space is kind of limited :)

Maybe the minimap could have a certain opacity, so it would not hide the curse

**Comment by evanbowman** [comment]
> Maybe the minimap could have a certain opacity, so it would not hide the curser

Great idea, but unfortunately this isn't easy to do on the gba. Opacity on the gba has to be applied to an entire tile layer, so I would have to give the whole menu overlay the same translucent appearance. Technically I could flicker the menu on and off at 30hz and it would look translucent on the gba screen due to inter frame blending, but not all emulators emulate this screen effect.

**Comment by Doronimmo** [comment]
> > Maybe the minimap could have a certain opacity, so it would not hide the curser
> 
> Great idea, but unfortunately this isn't easy to do on the gba. Opacity on the gba has to be applied to an entire tile layer, so I would have to give the whole menu overlay the same translucent appearance. Technically I could flicker the menu on and off at 30hz and it would look translucent on the gba screen due to inter frame blending, but not all emulators emulate this screen effect.

This would not really be an issue since most mainstream emulators (mgba,gpsp,vba) support this feature.

**Comment by evanbowman** [comment]
> This would not really be an issue since most mainstream emulators (mgba,gpsp,vba) support this feature.

I'll consider doing it this way! But I won't be able to do it right away, it'll take more time to do correctly. Originally, when I created the minimap for weapon targeting, I placed it in a portion of the screen where it could never possibly block the area around the cursor, so I haven't had to think about the minimap blocking players' view of things until now.

**Comment by evanbowman** [comment]
https://github.com/evanbowman/skyland-beta/releases/tag/2024.10.31.3

The minimap now displays the cursor, I'll keep playing around with the map idea.

**Comment by Doronimmo** [comment]
Maybe the minimap could display blocks on fire

**Comment by evanbowman** [comment]
> Maybe the minimap could display blocks on fire

![Skyland-105](https://github.com/user-attachments/assets/6e78ae31-363b-4fea-80a8-ecc2b9ccfc12)
I'm playing around with this idea
