### ISSUE TITLE
Graphical glitch in select menu

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#38]
![20241030_213553](https://github.com/user-attachments/assets/ba3f7e0d-b43d-454f-95fa-952454c8d6de)

**Comment by evanbowman** [comment]
ah! So The menu is _supposed_ to anchor its left corner or its right corner to the thing being selected to fit the menu fully within the screen. But because the pin crewmember and crewmember icon options are accidentally included, the width of the menu is larger than expected and neither anchoring position works correctly based on the camera position.

**Comment by evanbowman** [comment]
This no longer happens after I removed the erroneous crew options https://github.com/evanbowman/skyland-beta/releases
