### ISSUE TITLE
Move blocks mycelium

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#52]
In the fire bride challenge the mycelium is not salvageable but it is movable

**Comment by evanbowman** [comment]
Originally I prevented salvaging mycelium to prevent people from mining infinite coins from a regenerating block. I'll fix it properly by allowing salvaging but giving players zero resources.

**Comment by Doronimmo** [comment]
> Originally I prevented salvaging mycelium to prevent people from mining infinite coins from a regenerating block. I'll fix it properly by allowing salvaging but giving players zero resources.

Wouldn't this ruin the fire bridge challenge?

**Comment by evanbowman** [comment]
Yeah, it kind of would. Hmm...

**Comment by evanbowman** [comment]
Until recently you couldn't move mycelium blocks either. But by moving a selection of multiple blocks at once, where one of them happened to be a mycelium block, the game would still let you do it. So I temporarily disabled the check that prevents moving mycelium, because it was possible anyway via an obscure method. I guess I should go back and fix it

**Comment by evanbowman** [comment]
Fixed: https://github.com/evanbowman/skyland-beta/releases/tag/2024.11.1.3
