### ISSUE TITLE
ENHANCEMENT - select menu info popup

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#64]
The select menu is pretty self explanatory, but the info popup shows once every time you open the game, maybe it could appear once time in a new save file

**Comment by evanbowman** [comment]
There's an option to not remind you again:
![Skyland-103](https://github.com/user-attachments/assets/fe694f3c-3600-4bf1-ba9b-c378ae67a3f3)

I could re-order the options so that the first choice is the one to not remind you. I could change the options so that they are:
- I understand!
- Remind me again later

**Comment by Doronimmo** [comment]
oh, I'm dumb, sorry.

**Comment by Doronimmo** [comment]
I guess I closed the menu so fast that I did not even see the option :)
