### ISSUE TITLE
issue when building

### ISSUE THREAD

**Issue by Doronimmo** [evanbowman/skyland-beta#87]
installed all dependencies, ran the scripts but got this error 
`./build.sh: line 2: ninja: command not found
cp: cannot stat 'SkylandEngine': No such file or directory
creating fs.bin...
encoding 366 files...
encoded 19230824 bytes
done!
cat: SkylandEngine.gba: No such file or directory`
after manually adding the SkylandEngine.gba it worked, but I tink that this is the files that should be built.

**Comment by evanbowman** [comment]
ninja: command not found
This error might mean that the ninja build tool is not installed. Can you try using `make` instead? Change the ninja command in build.sh to `make`

**Comment by Doronimmo** [comment]
this error with make `rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
rebuilding image...
-- Configuring done (0.5s)
-- Generating done (0.1s)
-- Build files have been written to: /home/user/skyland-beta/build
make[1]: CMakeFiles/Makefile2: Nolo such file or directory
make[1]: *** No rule to make target 'CMakeFiles/Makefile2'.  Stop.
make: *** [Makefile:91: all] Error 2
cp: cannot stat 'SkylandEngine': No such file or directory
creating fs.bin...
encoding 366 files...
encoded 19230824 bytes
done!
cat: SkylandEngine.gba: No such file or directory`
looks like some makefile is missing

**Comment by Doronimmo** [comment]
Ah, got it working, removed the & before `__rom_end__` in line 295, probably broke the saveing feature.

**Comment by evanbowman** [comment]
> Ah, got it working, removed the & before `__rom_end__` in line 295, probably broke the saveing feature.

The compiler array-bounds error check is wrong here, the & before __rom_end__ is very much needed.

`__rom_end__` is a linker symbol referring to the end of the rom. To get the address of the end of the rom, we need to use the address-of operator `&`. The compiler sees us reading past the end of the rom and throws an array bounds error. But because we attach scripts and data at the end of the rom, reading past the rom end is very much intended behavior.

source/platform/gba/filesystem.cpp has an example of disabling the array bounds check (see `#pragma GCC diagnostic ignored "-Warray-bounds"`)

**Comment by evanbowman** [comment]
Further explanation:
u32(&__rom_end__ - 0x8000000) + filesystem::size()

0x8000000 is the address in the gba memory layout where rom begins. rom_end minus the start address gives us the rom size. Adding the appended fs.bin size (filesystem::size()) gives us the total size of the engine rom and the appended files. Many bootleg cartridges don't have a save battery. So to persist save data, we have to write save info back into same flash chip where the rom is saved. We don't want to overwrite the rom, so we need to know how big the rom is so that we can avoid writing to that region of the flash cart.

**Comment by Doronimmo** [comment]
#88
